apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: securityms
  name: securityms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: securityms
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: securityms
    spec:
      containers:
      - env:
        - name: projectms.service.address
          value: http://projectms:8082
        - name: alpha.cluster.address
          value: alphaserver:8080
        - name: spring.datasource.password
          value: 
        - name: spring.datasource.url
          value: 
        - name: spring.datasource.username
          value: 
        image: firstregistrypoc.azurecr.io/securityms:v1
        imagePullPolicy: Always
        name: securityms
        ports:
        - containerPort: 8081
        resources: {}
      hostname: securityms
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: securityms
  name: securityms
spec:
  type: LoadBalancer
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: securityms
status:
  loadBalancer: {}
---
